-- CREATE TABLE burgers(
--   id INT NOT NULL AUTO_INCREMENT,
--   title VARCHAR(80),
--   price INT,
--   toppings VARCHAR(255),
--   isAvailable TINYINT, 
--   PRIMARY KEY (id)
-- )

-- INSERT INTO burgers (
--   title, 
--   price,
--   toppings,
--   isAvailable
-- )

-- VALUES (
--   "Beefy",
--   5, 
--   "Beef, cheese, tomato",
--   true
-- )